version: '3.4'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q2ntW8An1J2mkQQUwGcR
      - POSTGRES_DB=potatoai
    ports:
      - '6970:5432'
    volumes:
      - db:/var/lib/postgresql/potatoai-data
  nats:
    image: 'nats:latest'
    command: "-DV -js --user thisisnats --pass f1f18a162944a3b"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats-server
volumes:
  db:
    driver: local
